# Generated by Django 5.1 on 2024-10-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reporter_name", models.CharField(max_length=100)),
                ("reporter_email", models.EmailField(max_length=254)),
                ("reporter_ph", models.CharField(blank=True, max_length=15, null=True)),
                ("news_description", models.TextField()),
                ("news_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
