# Generated by Django 5.1 on 2024-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.CharField(default='20', max_length=128),
        ),
    ]
